[package]
name = "cog"
version = "0.0.1"
description = "A ed-like text editor"
license = "Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"

[[bin]]
name = "cog"
path = "src/main.rs"
